on: [push]

jobs:
  test-everywhere:
    name: Test Action on all platforms
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Run the action
        uses: potatoqualitee/sqlsuite@initial
        with:
          install: docker, sqlcmd
