on: [push]

jobs:
  run-on-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Create variables for module cacher
        uses: potatoqualitee/sqlsuite@initial
        with:
          install: sqlcmd, docker

      - name: Run sqlcmd
        run: sqlcmd -S localhost -U sa -P dbatools.I0 -d tempdb -Q "SELECT @@version;"
